version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: defect-tracker-backend
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - defect-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: defect-tracker-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - defect-tracker-network

networks:
  defect-tracker-network:
    driver: bridge